<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: sans-serif;
            color: #333;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #2d3748;
        }
        .header p {
            margin: 5px 0 0;
            color: #718096;
        }
        .video-item {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .video-title {
            font-size: 18px;
            font-weight: bold;
            color: #2d3748;
            margin-bottom: 5px;
        }
        .video-meta {
            font-size: 12px;
            color: #718096;
            margin-bottom: 10px;
        }
        .video-summary {
            font-size: 14px;
            background: #f7fafc;
            padding: 15px;
            border-radius: 5px;
        }
        a {
            color: #3182ce;
            text-decoration: none;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #cbd5e0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $date }}</p>
    </div>

    @foreach($videos as $video)
        <div class="video-item">
            <div class="video-title">
                <a href="https://www.youtube.com/watch?v={{ $video->video_id }}" target="_blank">
                    {{ $video->title }}
                </a>
            </div>
            <div class="video-meta">
                {{ $video->channel_title }} • {{ gmdate("H:i:s", $video->duration) }}
            </div>
            <div class="video-summary">
                @if($video->summary_detailed)
                    {!! Str::markdown($video->summary_detailed) !!}
                @else
                    <p>No summary available.</p>
                @endif
            </div>
        </div>
    @endforeach

    <div class="footer">
        Generated by SaaS Automation
    </div>
</body>
</html>
