<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $video->title }}</title>
    <style>
        body {
            font-family: sans-serif;
            color: #333;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
        }
        .header h1 {
            margin: 0;
            color: #2d3748;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #718096;
        }
        .meta {
            text-align: center;
            font-size: 12px;
            color: #718096;
            margin-bottom: 20px;
        }
        .content {
            background: #f7fafc;
            padding: 20px;
            border-radius: 5px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #cbd5e0;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $video->title }}</h1>
    </div>
    
    <div class="meta">
        {{ $video->channel_title }} • {{ $video->duration }} • {{ $video->published_at }}
    </div>

    <div class="content">
        <h3>Summary</h3>
        @if($video->summary_detailed)
            {!! Str::markdown($video->summary_detailed) !!}
        @elseif($video->summary_short)
            {!! Str::markdown($video->summary_short) !!}
        @else
            <p>No summary available.</p>
        @endif
    </div>

    @if($video->transcript)
    <div style="margin-top: 30px;">
        <h3>Transcript Excerpt (First 500 words)</h3>
        <p style="font-size: 12px; color: #666;">
            {{ Str::limit(strip_tags(implode(' ', array_column($video->transcript, 'text'))), 3000) }}
        </p>
    </div>
    @endif

    <div class="footer">
        Generated by SaaS Automation
    </div>
</body>
</html>
